//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.Albums = new HashSet<Album>();
            this.Posts = new HashSet<Post>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual UserMeta UserMeta { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<Post> Posts { get; set; }
    }
}
